[tool.ruff]
line-length = 120
fix = true
exclude = [
  ".venv",
  "migrations",
  "tests.py"
]
[tool.ruff.lint]
select = [
  "E",
  "F",
  'I',
]
[tool.ruff.lint.pydocstyle]
convention = "numpy"
[tool.ruff.lint.mccabe]
max-complexity = 5
